spring:
  application:
    name: whitebird-config-service
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/whitebird-project/whitebird
          search-paths: whitebird-config-folder
        bootstrap: true
      allow-override: true
server:
  port: 11012
