spring:
  application:
    name: whitebird-config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
        bootstrap: true
      allow-override: true
    consul:
      host: ${CONSUL_HOST}
      discovery:
        heartbeat:
          enabled: true
server:
  port: 11012
