version: "3.7"
services:
  consul:
    image: consul:latest
    ports:
      - 8500:8500
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mysql:
    image: mysql:8
    ports:
      - 10000:3306
    environment:
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ~/data/mysql:/var/lib/mysql
