spring:
  application:
    name: whitebird-demo-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.uuid}}}
server:
  port: 11011
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:11010/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:11010/oauth/token
      grant-type: password
      scope: server
