spring:
  cloud:
    config:
      allow-override: true
  flyway:
    baseline-on-migrate: true
    check-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,health'
  metrics:
    tags:
      application: ${spring.application.name}
whitebird:
  swagger:
    enabled: true
    base-package: top.idwangmo
    version: 1.0
    title: ${spring.application.name}
    license: MIT