spring:
  datasource:
    url: jdbc:mysql://localhost:10000/whitebird_auth_service
    username: root
    password: root

server:
  port: 11010

whitebird:
  swagger:
    enabled: true
    base-package: top.idwangmo
    version: 1.0
    title: whitebitd-auth-service
    license: MIT