spring:
  application:
    name: whitebird-spring-boot-server

  boot:
    admin:
      discovery:
        # 忽略发现服务
        ignored-services: consul

server:
  port: 11012

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:11010/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:11010/oauth/token
      grant-type: password
      scope: server
      user-authorization-uri: http://localhost:11010/oauth/token