global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
scrape_configs:
  - job_name: node
    metrics_path: /metrics
    scheme: http
    consul_sd_configs:
      - server: consul:8500
        scheme: http
        services:
          - node_exporter
    relabel_configs:
      - source_labels:  ["__meta_consul_dc"]
        regex: "(.*)"
        replacement: $1
        action: replace
        target_label: "dc"
      - source_labels: ["__meta_consul_tags"]
        regex: ".*,development,.*"
        action: keep